// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  maxCharCodigoProd: 6,
  adminClave: '123456',
  preURL: 'https://nevilwebtesting.xyz/apis/api/',
  preURL2: 'https://nevilwebtesting.xyz/apis',
  TestURL: '',
  postURL: '',
  horarioCanchaURL:'horario/cancha',
  elementoEntrada:'?elementoEntrada=',
  provinciasURL: 'Provincias',
  cantonesURL: 'Cantones',
  distritosURL: 'Distritos',
  usuariosURL: 'Usuarios/',
  posicionesURL: 'Posiciones/',
  retosEnviadosURL:'reservaciones-enviadas',
  retosRecibidosURL:'reservaciones-recibidas',
  equiposURL: 'Equipos/',
  generarFacturaURL:'generar-factura/',
  consultaeFacturaURL:'consultar-factura/',
  canchasURL: 'Canchas/',
  categoriaCanchasURL: 'Categoriacanchas/',
  bloqueoCanchasURL: 'reservaciones',
  confirmacionReservacionesURL: 'confirmacionReservaciones',
  bloqueoCanchaGet: 'bloqueo/canchas',
  reservacionesUrl: 'Reservaciones/',
  codUsuarioParam:'?Cod_Usuario=',
  partidoActualURL: 'partido-actual/',
  iniciarPartidoURL: 'iniciar-partido/',
  actualizarQrURL: 'actualizar-qr/',
  codPartido:'?Cod_Partido=',
  evaluacionJugador:'evaluacion-jugador/',
  evaluacionEquipo:'evaluacion-equipo/',
  actualizarPartidoURL: 'actualizar-partido/',
  codUsuarioSecondParam:'&Cod_Usuario=',
  loginURL: 'login',
  actualizarDatos : 'actualizar-datos-usuario',
  imageURLCheck: 'https://nevilwebtesting.xyz/apis/',
  correoParam:'?correo=',
  locationParam:'?location=',
  contrasenaPatam:'&contrasena=',
  codCanchaParam:'?Cod_Cancha=',
  codEquipoParam:'?Cod_Equipo=',
  canchaUsuarioParam:'cancha/usuario',
  perfilCancha:'perfil-cancha/',
  perfilUsuario:'perfil-usuario/',
  fitrarUsuarios:'filtrar-usuarios/',
  fitrarCanchas:'filtrar-canchas/',
  fitrarEquipos:'filtrar-equipos/',
  horarioCanchasUrl:'horario/cancha',
  actualizaHorarrioCanchaURL: 'actualizar/horario/cancha',
  jugadoresEquiposURL:'jugadores-equipos/',
  reservacionesFecha: 'reservaciones/fecha',
reservacionesFechaHora: 'reservaciones/fecha/hora',
canchasURLParam: 'cancha/usuario',
reservacionesFechaHoraInicio: 'reservaciones/fecha/hora/inicio',
reservacionesFechaHoraFin: 'reservaciones/fecha/hora/fin',
deleteReservacionesURL:'Reservaciones/',
actualizaFotoUsuarioURL:'actualizar-foto-usuario/',
actualizaFotoEquipoURL:'actualizar-foto-equipo/',
codReservacion:'?Cod_Reservacion=',
fechaParam: '&Fecha=',
horaInicio:'&Hora_Inicio=',
horaFin:'&Hora_Fin=',
  Cod_Provincia:'?Cod_Provincia=',
  AvatarParam:'&Avatar=',
  FotoParam:'&Foto=',
  Cod_Provincia_Param:'&Cod_Provincia=',
  Cod_Posicion_Param:'&Cod_Posicion=',
  Peso_Param:'&Peso=',
 Precio_Hora_Param:'&Precio_Hora=',
 Estatura_Param:'&Estatura=',
  Cod_Canton:'?Cod_Canton=',
  Cod_Canton_Param:'&Cod_Canton=',
  Cod_Distrito:'?Cod_Distrito=',
  Cod_Distrito_Param:'&Cod_Distrito=',
  Cod_Categoria_Param:'&Cod_Categoria=',
 SolicitudesEquiposURL:'solicitudes-equipos/',
 SolicitudesJugadoresURL:'solicitudes-jugadores/',
 SolicitudesJugadoresEquiposPostURL:'solicitud-jugadores-equipos',
 jugadoresEquiposPostURL:'jugador-equipo',
 SolicitudesJugadoresEquiposPutURL:'solicitud-jugadores-equipos',
 SolicitudesJugadoresEquiposDeleteURL:'solicitud-jugadores-equipos/',
 codSolicitudParam:'?Cod_solicitud=',
  codReservacionParam:'&Cod_Reservacion=',
  codConfirmacionUsuarioParam:'&Confirmacion_Usuario=',
  codConfirmacionEquipoParam:'&Confirmacion_Equipo=',
  codEstadoParam:'&Estado=',
  FiltrarFecha:'reservaciones/filtrar-fecha/',
  gestorImagenesURL:'ImageAPI/UploadFile/',
  oldFileName:"&oldFileName=",
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  prdMode: false,
 // url:'http://192.168.178.30:3000'
 perfilUsuarioURL:'perfil-usuario/',
 perfilCanchaURL:'perfil-cancha/',
 perfilEquipoURL:'perfil-equipo/',
 misEquiposURL:'mis-equipos/',
 otrosEquiposURL:'otros-equipos/',
 misCanchasURL:'mis-canchas/',
 reservacionesRecibidasUrl:'reservaciones-recibidas',
 reservacionesEnviadasUrl:'reservaciones-enviadas',
 reservacionesConfirmadasUrl:'reservaciones-confirmadas',
 reservacionesHistorialUrl:'reservaciones-historial',
 reservacionURL:'reservacion',
 actualizarReservacionURL:'actualizar-reservacion',
 actuzalizarContrasenaURL: 'actualizar-contrasena/',
 Codigo_TokenParam: '&Codigo_Token=',
 Codigo_Token:'?Codigo_Token=',
Expiracion_TokenParam:'&Expiracion_Token=',
Expiracion_Token: '&Expiracion_Token=',
ContrasenaParam:'&Contrasena=',
Contrasena: '&Contrasena=',
 actualizarTokenURL: 'actualizar-token/',
 apiCorreoURL:'correo/',
 reservacionesFiltroURL:'reservaciones-fecha-filtro',
 Fecha_Inicio:'&Fecha_Inicio=',
 Fecha_Fin:'&Fecha_Fin=',
 reservacionesFuturasURL : 'reservaciones/futuras/',
fechaSecondParam: '&Fecha=',
reservacionesDesactivadasURL:'reservaciones/desactivadas',
putReservacionesEstadoURL:'reservacion-estado/',
codEstadoParam2:'&Cod_Estado=',
posicionActualURL:'posicion-actual',
evaluacionEquiposURL:'evaluacion-equipos',
partidosJugadorURL:'partidos-jugados/',
jugadorFutplayURL:'jugador-futplay/'
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
