
export const environment = {
  production: true,
  maxCharCodigoProd: 6,
  preURL: 'https://futplaycompany.com/production/api/',
  preURL2: 'https://futplaycompany.com/production/api/',
  getUserIMG:'get/usuarios/foto/',
  TestURL: '',
  postURL: '',
  getProvinciasURL: 'get/provincias',
  getCantonesURL: 'get/cantones/provincias/',
  getDistritosURL: 'get/distritos/cantones/',
  getUsuarioCanchasURL:'get/canchas/',
  getCategoriasURL:'get/categorias',
  getListaCanchasURL:'get/lista/canchas',
  getMisEquiposURL: 'get/mis/equipos/',
  getPosicionesURL:'get/posiciones',
  getListaEquiposURL: 'get/lista/equipos/',
  getListaUsuariosURL: 'get/lista/usuarios/',
  getClasificacionEquiposURL: 'get/clasificacion/equipos',
  getConsultarDisponiblidadReservacionURL:'get/disponibilidad/reservaciones/cancha/',
  getHorarioCanchaURL:'get/horario/cancha/',
  getReservacionesCanchaFechaURL:'get/reservaciones/cancha/',
  getReservacionesMovilURL:'get/reservaciones/movil/',
  getReservacionesEnviadasURL:'get/reservaciones/enviadas/usuario/',
  getReservacionesRevisionURL:'get/reservaciones/revision/usuario/',
  getReservacionesCanceladasURL:'get/reservaciones/canceladas/usuario/',
  getReservacionesAbiertasURL:'get/reservaciones/abiertas',
  getReservacionesHistorialURL:'get/reservaciones/historial/usuario/',
  getReservacionesRecibidassURL:'get/reservaciones/recibidas/usuario/',
  getReservacionesConfirmadassURL:'get/reservaciones/confirmadas/usuario/',
  getLoginURL: 'get/login-in-movil/',
  postUserURL:'post/usuario',
  postForgotPassword:'post/forgot/password',
  postSolicitudesURL:'post/solicitudes/equipo/',
  getSolicitudesRecibidasEquipoURL:'get/solicitudes/recibidas/equipo/',
  getSolicitudesRecibidasUsuarioURL:'get/solicitudes/recibidas/usuario/',
  getSolicitudesEnviadasEquipoURL:'get/solicitudes/enviadas/equipo/',
  getSolicitudesEnviadasUsuarioURL:'get/solicitudes/enviadas/usuario/',
  postTokenVerification:'post/token/verification',
  postUserPassword:'post/usuario/password',
  postCanchaURL:'post/canchas',
  postFotoCanchaURL:'post/foto/cancha/',
  postFotoUsuarioURL:'post/foto/usuario/',
  postHorarioCanchaURL:'post/horario/cancha/',
  deleteCanchaURL:'delete/cancha/',
  postReservacionCanchaURL:'post/reservacion/cancha/',
  putReservacionURL:'put/reservacion/',
  postDetalleReservacionURL:'post/detalle/reservacion/',
  postEquipoURL: 'post/equipo',
  postDurezaEquipoURL: 'post/dureza/equipo/',
  postFotoEquipoURL:'post/foto/equipo/',
  getJugadoresEquipoURL: 'get/jugadores/equipo/',
  getJugadorURL: 'get/jugador/',
  putEquipoURL: 'put/equipo/',
  deleteEquipoURL: 'delete/equipo/',
  getJugadoresEquiposURL:'get/jugadores/equipo/',
  getReservacionesFuturas:'get/reservaciones/futuras/',
  getPartidoURL:'get/partido/reservacion/',
  postJugadoresEquiposURL:'post/jugadores/equipo/',
  putJugadoresEquiposURL:'put/jugadores/equipo/',
  putSolicitudURL:'put/solicitud/',
  putPartidoCodigoQR:'put/partido/codigoqr/',
  putDetalleReservacionURL:'put/detalle/reservacion/',
  deleteJugadoresEquiposURL:'delete/jugadores/equipo/',
  putCanchaURL:'put/canchas/',
  putUsuarioURL:'put/usuario/',
  putJugadorFutplayURL:'put/usuario/jugador/futplay/',
  putJugadorDelPartidoURL:'put/usuario/jugador/del/partido/',
  putHorarioCanchaURL:'put/horario/cancha/',
  putCanchaEstadoURL:'put/estado/cancha/',
  deleteReservacionesURL:'delete/reservacion/',
  

  getFiltroEquiposURL:'get/filtro/equipos/',
  getFiltroCanchasURL:'get/filtro/canchas/',
  getFiltroUsuariosURL:'get/filtro/usuarios/',
  getUsuario:'get/usuario/',

  putUsuarioAvatarURL:'put/avatar/usuario/',
  putEquiposAvatarURL:'put/avatar/equipo/',
  postReservacionCorreo:'post/correo',
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  deleteUser:'delete/usuario/',
  putPartidoURL:'put/partido/',
  finalizarPartidoURL:'put/finalizar/partido/',
  prdMode: false,
  iosSDK:'ca-app-pub-3191879076705982~3698122494',
  iosInterstitial:'ca-app-pub-3191879076705982/3638052631',   
  androidSDK:'ca-app-pub-3191879076705982~8866688691',
  androidInterstitial:'ca-app-pub-3191879076705982/3246336240',


  getPerfilEquipo:'get/perfil/equipo/',
  getPerfilCancha:'get/perfil/cancha/',

  // usuario geolocalizacion
  getUsuarioGeolocalizacion:'get/usuario/geolocalizacion/',
  postUsuarioGeolocalizacion:'post/usuario/geolocalizacion',
  putUsuarioGeolocalizacion:'put/usuario/geolocalizacion/',
  deleteUsuarioGeolocalizacion:'delete/usuario/geolocalizacion/',

    // equipo geolocalizacion
    getEquipoGeolocalizacion:'get/equipo/geolocalizacion/',
    postEquipoGeolocalizacion:'post/equipo/geolocalizacion',
    putEquipoGeolocalizacion:'put/equipo/geolocalizacion/',
    deleteEquipoGeolocalizacion:'delete/equipo/geolocalizacion/',

       // Descuentos

       getCodigosDesciuentosURL:'get/descuento/codigo/',
       //PAGOS
   
       getVerificacionPagoURL:'get/verificacion/pago/',
       postVerificacionPagoURL:'post/verificacion/pago',
       putVerificacionPagoURL:'put/verificacion/pago/',
       archivosURL:'https://futplaycompany.com/production/api/get/file/',
};