
export const environment = {
  production: true,
  maxCharCodigoProd: 6,
  adminClave: '123456',
  preURL: 'https://futplaycompany.com/FUTPLAY_APIS_HOST/api/',
  preURL2: 'https://futplaycompany.com/FUTPLAY_APIS_HOST/api/',
  TestURL: '',
  reservacionesHistorialUrl:'reservaciones-historial',
  reservacionURL:'reservacion',
  postURL: '',
  provinciasURL: 'Provincias',
  cantonesURL: 'Cantones',
  distritosURL: 'Distritos',
  usuariosURL: 'Usuarios/',
  elementoEntrada:'?elementoEntrada=',
  posicionesURL: 'Posiciones/',
  retosEnviadosURL:'reservaciones-enviadas',
  retosRecibidosURL:'reservaciones-recibidas',
  equiposURL: 'Equipos/',
  canchasURL: 'Canchas/',
  generarFacturaURL:'generar-factura/',
  consultaeFacturaURL:'consultar-factura/',
  categoriaCanchasURL: 'Categoriacanchas/',
  bloqueoCanchasURL: 'reservaciones',
  confirmacionReservacionesURL: 'confirmacionReservaciones',
  codPartido:'?Cod_Partido=',
  bloqueoCanchaGet: 'bloqueo/canchas',
  reservacionesUrl: 'Reservaciones/',
  codUsuarioParam:'?Cod_Usuario=',
  partidoActualURL: 'partido-actual/',
  iniciarPartidoURL: 'iniciar-partido/',
  actualizarQrURL: 'actualizar-qr/',
  evaluacionJugador:'evaluacion-jugador/',
  evaluacionEquipo:'evaluacion-equipo/',
  actualizarPartidoURL: 'actualizar-partido/',
  codUsuarioSecondParam:'&Cod_Usuario=',
  loginURL: 'login',
  actualizarDatos : 'actualizar-datos-usuario',
  imageURLCheck: 'https://nevilwebtesting.xyz/apis/',
  correoParam:'?correo=',
  locationParam:'?location=',
  contrasenaPatam:'&contrasena=',
  codCanchaParam:'?Cod_Cancha=',
  codEquipoParam:'?Cod_Equipo=',
  canchaUsuarioParam:'cancha/usuario',
  perfilCancha:'perfil-cancha/',
  perfilUsuario:'perfil-usuario/',
  fitrarUsuarios:'filtrar-usuarios/',
  fitrarCanchas:'filtrar-canchas/',
  fitrarEquipos:'filtrar-equipos/',
  horarioCanchasUrl:'horario/cancha',
  actualizaHorarrioCanchaURL: 'actualizar/horario/cancha',
  jugadoresEquiposURL:'jugadores-equipos/',
  reservacionesFecha: 'reservaciones/fecha',
reservacionesFechaHora: 'reservaciones/fecha/hora',
canchasURLParam: 'cancha/usuario',
reservacionesFechaHoraInicio: 'reservaciones/fecha/hora/inicio',
reservacionesFechaHoraFin: 'reservaciones/fecha/hora/fin',
deleteReservacionesURL:'Reservaciones/',
actualizaFotoUsuarioURL:'actualizar-foto-usuario/',
actualizaFotoEquipoURL:'actualizar-foto-equipo/',
codReservacion:'?Cod_Reservacion=',
fechaParam: '&Fecha=',
horaInicio:'&Hora_Inicio=',
horaFin:'&Hora_Fin=',
  Cod_Provincia:'?Cod_Provincia=',
  AvatarParam:'&Avatar=',
  FotoParam:'&Foto=',
  Cod_Provincia_Param:'&Cod_Provincia=',
  Cod_Posicion_Param:'&Cod_Posicion=',
  Peso_Param:'&Peso=',
 Precio_Hora_Param:'&Precio_Hora=',
 Estatura_Param:'&Estatura=',
  Cod_Canton:'?Cod_Canton=',
  Cod_Canton_Param:'&Cod_Canton=',
  Cod_Distrito:'?Cod_Distrito=',
  Cod_Distrito_Param:'&Cod_Distrito=',
  Cod_Categoria_Param:'&Cod_Categoria=',
 SolicitudesEquiposURL:'solicitudes-equipos/',
 SolicitudesJugadoresURL:'solicitudes-jugadores/',
 SolicitudesJugadoresEquiposPostURL:'solicitud-jugadores-equipos',
 jugadoresEquiposPostURL:'jugador-equipo',
 SolicitudesJugadoresEquiposPutURL:'solicitud-jugadores-equipos',
 SolicitudesJugadoresEquiposDeleteURL:'solicitud-jugadores-equipos/',
 codSolicitudParam:'?Cod_solicitud=',
  codReservacionParam:'&Cod_Reservacion=',
  codConfirmacionUsuarioParam:'&Confirmacion_Usuario=',
  codConfirmacionEquipoParam:'&Confirmacion_Equipo=',
  codEstadoParam:'&Estado=',
  FiltrarFecha:'reservaciones/filtrar-fecha/',
  gestorImagenesURL:'ImageAPI/UploadFile/',
  oldFileName:"&oldFileName=",
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  prdMode: false,
 // url:'http://192.168.178.30:3000'
 perfilUsuarioURL:'perfil-usuario/',
 perfilCanchaURL:'perfil-cancha/',
 perfilEquipoURL:'perfil-equipo/',
 misEquiposURL:'mis-equipos/',
 misCanchasURL:'mis-canchas/',
 reservacionesRevisionUrl:'reservaciones-revision',
 reservacionesActualesUrl:'reservaciones-actuales',
 reservacionesRecibidasUrl:'reservaciones-recibidas',
 reservacionesEnviadasUrl:'reservaciones-enviadas',
 reservacionesConfirmadasUrl:'reservaciones-confirmadas',
 actualizarReservacionURL:'actualizar-reservacion',
 actuzalizarContrasenaURL: 'actualizar-contrasena/',
 Codigo_TokenParam: '&Codigo_Token=',
 Codigo_Token:'?Codigo_Token=',
Expiracion_TokenParam:'&Expiracion_Token=',
Expiracion_Token: '&Expiracion_Token=',
ContrasenaParam:'&Contrasena=',
Contrasena: '&Contrasena=',
 actualizarTokenURL: 'actualizar-token/',
 apiCorreoURL:'correo/',
 otrosEquiposURL:'otros-equipos/',
 reservacionesFiltroURL:'reservaciones-fecha-filtro',
 Fecha_Inicio:'&Fecha_Inicio=',
 Fecha_Fin:'&Fecha_Fin=',
 reservacionesFuturasURL : 'reservaciones/futuras/',
fechaSecondParam: '&Fecha=',
reservacionesDesactivadasURL:'reservaciones/desactivadas',
putReservacionesEstadoURL:'reservacion-estado/',
codEstadoParam2:'&Cod_Estado=',
horarioCanchaURL:'horario/cancha',
posicionActualURL:'posicion-actual',
evaluacionEquiposURL:'evaluacion-equipos',
partidosJugadorURL:'partidos-jugados/',
jugadorFutplayURL:'jugador-futplay/',
jugadorDelPartidoURL:'jugador-partido',
clasificacionURL:'clasificacion',
eliminarEquipo :'borrar/equipo/reservaciones/?Cod_Equipo=',
eliminarUsuario:'usuarios?Cod_Usuario='
};