
export const environment = {
  production: false,
  maxCharCodigoProd: 6,
  preURL: 'https://futplaycompany.com/api_test/api/',
  preURL2: 'https://futplaycompany.com/api_test/api/',
  TestURL: '',
  postURL: '',
  getProvinciasURL: 'get/provincias',
  getCantonesURL: 'get/cantones/provincias/',
  getDistritosURL: 'get/distritos/cantones/',
  getUsuarioCanchasURL:'get/canchas/',
  getCategoriasURL:'get/categorias',
  getListaCanchasURL:'get/lista/canchas',
  getMisEquiposURL: 'get/mis/equipos/',
  getPosicionesURL:'get/posiciones',
  getListaEquiposURL: 'get/lista/equipos/',
  getListaUsuariosURL: 'get/lista/usuarios/',
  getClasificacionEquiposURL: 'get/clasificacion/equipos',
  getConsultarDisponiblidadReservacionURL:'get/disponibilidad/reservaciones/cancha/',
  getHorarioCanchaURL:'get/horario/cancha/',
  getReservacionesCanchaFechaURL:'get/reservaciones/cancha/',
  getReservacionesMovilURL:'get/reservaciones/movil/',
  getReservacionesEnviadasURL:'get/reservaciones/enviadas/usuario/',
  getReservacionesRecibidassURL:'get/reservaciones/recibidas/usuario/',
  getReservacionesConfirmadassURL:'get/reservaciones/confirmadas/usuario/',
  getLoginURL: 'get/login-in-movil/',
  postUserURL:'post/usuario',
  postForgotPassword:'post/forgot/password',
  postSolicitudesURL:'post/solicitudes/equipo/',
  getSolicitudesRecibidasEquipoURL:'get/solicitudes/recibidas/equipo/',
  getSolicitudesRecibidasUsuarioURL:'get/solicitudes/recibidas/usuario/',
  getSolicitudesEnviadasEquipoURL:'get/solicitudes/enviadas/equipo/',
  getSolicitudesEnviadasUsuarioURL:'get/solicitudes/enviadas/usuario/',
  postTokenVerification:'post/token/verification',
  postUserPassword:'post/usuario/password',
  postCanchaURL:'post/canchas',
  postFotoCanchaURL:'post/foto/cancha/',
  postFotoUsuarioURL:'post/foto/usuario/',
  postHorarioCanchaURL:'post/horario/cancha/',
  deleteCanchaURL:'delete/cancha/',
  postReservacionCanchaURL:'post/reservacion/cancha/',
  postDetalleReservacionURL:'post/detalle/reservacion/',
  postEquipoURL: 'post/equipo',
  postFotoEquipoURL:'post/foto/equipo/',
  getJugadoresEquipoURL: 'get/jugadores/equipo/',
  putEquipoURL: 'put/equipo/',
  deleteEquipoURL: 'delete/equipo',
  getJugadoresEquiposURL:'get/jugadores/equipo/',
  getPartidoURL:'get/partido/reservacion/',
  postJugadoresEquiposURL:'post/jugadores/equipo/',
  putJugadoresEquiposURL:'put/jugadores/equipo/',
  putSolicitudURL:'put/solicitud/',
  putPartidoCodigoQR:'put/partido/codigoqr/',
  putDetalleReservacionURL:'put/detalle/reservacion/',
  deleteJugadoresEquiposURL:'delete/jugadores/equipo/',
  putCanchaURL:'put/canchas/',
  putUsuarioURL:'put/usuario/',
  putHorarioCanchaURL:'put/horario/cancha/',
  putCanchaEstadoURL:'put/estado/cancha/',
  deleteReservacionesURL:'delete/reservacion/',
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  deleteUser:'delete/usuario/',
  putPartidoURL:'put/partido/',
  prdMode: false
};