export const environment = {
  production: true,
  maxCharCodigoProd: 6,
  adminClave: '123456',
  preURL: 'https://dev-coding.com/FUTPLAY_APIS_HOST/api/',
  preURL2: 'https://dev-coding.com/FUTPLAY_APIS_HOST/',
  TestURL: '',
  posicionesURL: 'Posiciones/',
  postURL: '',
  iniciarPartidoURL: 'iniciar-partido/',
  actualizarQrURL: 'actualizar-qr"/',
  partidoActualURL: 'partido-actual/',
  actualizarPartidoURL: 'actualizar-qr"/',
  provinciasURL: 'Provincias',
  cantonesURL: 'Cantones',
  horarioCanchasUrl:'horario/cancha',
  actualizaHorarrioCanchaURL: 'actualizar/horario/cancha',
  loginURL: 'login',
  confirmacionReservacionesURL: 'confirmacionReservaciones',
  retosEnviadosURL:'reservaciones-enviadas',
  retosRecibidosURL:'reservaciones-recibidas',
  perfilCancha:'perfil-cancha/',
  perfilUsuario:'perfil-usuario/',
  jugadoresEquiposURL:'jugadores-equipos/',
  evaluacionJugador:'evaluacion-jugador/',
  evaluacionEquipo:'evaluacion-equipo/',
  SolicitudesEquiposURL:'solicitudes-equipos/',
  SolicitudesJugadoresURL:'solicitudes-jugadores/',
  SolicitudesJugadoresEquiposPostURL:'solicitud-jugadores-equipos',
  SolicitudesJugadoresEquiposPutURL:'solicitud-jugadores-equipos',
  SolicitudesJugadoresEquiposDeleteURL:'solicitud-jugadores-equipos/',
  codSolicitudParam:'?Cod_solicitud=',
  jugadoresEquiposPostURL:'jugadores-equipos',
  codConfirmacionUsuarioParam:'&Confirmacion_Usuario=',
  codConfirmacionEquipoParam:'&Confirmacion_Equipo=',
  codEstadoParam:'&Estado=',

  correoParam:'?correo=',
  contrasenaPatam:'&contrasena=',
   distritosURL: 'Distritos',
  usuariosURL: 'Usuarios/',
  equiposURL: 'Equipos/',
  canchasURL: 'Canchas/',
  categoriaCanchasURL: 'Categoriacanchas/',
  bloqueoCanchasURL: 'reservaciones',
  bloqueoCanchaGet: 'bloqueo/canchas',
  reservacionesUrl: 'Reservaciones',
  deleteReservacionesURL:'Reservaciones/',
  codUsuarioParam:'?Cod_Usuario=',
  codReservacionParam:'&Cod_Reservacion=',
  codReservacion:'?Cod_Reservacion=',
  codUsuarioSecondParam:'&Cod_Usuario=',
  codCanchaParam:'?Cod_Cancha=',
  canchaUsuarioParam:'cancha/usuario',
  canchasURLParam: 'cancha/usuario',
  reservacionesFechaHora: 'reservaciones/fecha/hora',
  fechaParam: '&Fecha=',
  horaInicio:'&Hora_Inicio=',
  reservacionesFechaHoraInicio: 'reservaciones/fecha/hora/inicio',
reservacionesFechaHoraFin: 'reservaciones/fecha/hora/fin',
  horaFin:'&Hora_Fin=',
  reservacionesFecha: 'reservaciones/fecha',
  Cod_Provincia:'?Cod_Provincia=',
  Cod_Provincia_Param:'&Cod_Provincia=',
  Cod_Canton:'?Cod_Canton=',
  Cod_Canton_Param:'&Cod_Canton=',
  Cod_Distrito:'?Cod_Distrito=',
  Cod_Distrito_Param:'&Cod_Distrito=',
  codDistritoParam:'?Cod_Distrito=',
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  prdMode: false,
  codEquipoParam:'?Cod_Equipo=',
  perfilUsuarioURL:'perfil-usuario/',
  perfilCanchaURL:'perfil-cancha/',
  perfilEquipoURL:'perfil-equipo/',
  misEquiposURL:'mis-equipos/',
  misCanchasURL:'mis-canchas/',
  reservacionesRecibidasUrl:'reservaciones-recibidas',
  reservacionesEnviadasUrl:'reservaciones-enviadas',
  reservacionesConfirmadasUrl:'reservaciones-confirmadas',
  actualizarReservacionURL:'actualizar-reservacion',
};
