
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'1', N'San José')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'2', N'Escazú')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'3', N'Desamparados')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'4', N'Puriscal')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'5', N'Tarrazú')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'6', N'Aserrí')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'7', N'Mora')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'8', N'Goicoechea')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'9', N'Santa Ana')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'10', N'Alajuelita')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'11', N'Vásquez de Coronado')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'12', N'Acosta')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'13', N'Tibás')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'14', N'Moravia')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'15', N'Montes de Oca')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'16', N'Turrubares')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'17', N'Dota')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'18', N'Curridabat')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'19', N'Pérez Zeledón')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'1', N'20', N'León Cortéz Castro')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'1', N'Alajuela')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'2', N'San Ramón')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'3', N'Grecia')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'4', N'San Mateo')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'5', N'Atenas')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'6', N'Naranjo')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'7', N'Palmares')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'8', N'Poás')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'9', N'Orotina')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'10', N'San Carlos')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'11', N'Zarcero')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'12', N'Valverde Vega')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'13', N'Upala')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'14', N'Los Chiles')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'2', N'15', N'Guatuso')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'1', N'Cartago')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'2', N'Paraíso')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'3', N'La Unión')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'4', N'Jiménez')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'5', N'Turrialba')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'6', N'Alvarado')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'7', N'Oreamuno')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'3', N'8', N'El Guarco')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'1', N'Heredia')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'2', N'Barva')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'3', N'Santo Domingo')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'4', N'Santa Bárbara')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'5', N'San Rafael')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'6', N'San Isidro')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'7', N'Belén')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'8', N'Flores')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'9', N'San Pablo')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'4', N'10', N'Sarapiquí')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'1', N'Liberia')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'2', N'Nicoya')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'3', N'Santa Cruz')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'4', N'Bagaces')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'5', N'Carrillo')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'6', N'Cañas')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'7', N'Abangares')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'8', N'Tilarán')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'9', N'Nandayure')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'10', N'La Cruz')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'5', N'11', N'Hojancha')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'1', N'Puntarenas')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'2', N'Esparza')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'3', N'Buenos Aires')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'4', N'Montes de Oro')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'5', N'Osa')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'6', N'Aguirre')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'7', N'Golfito')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'8', N'Coto Brus')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'9', N'Parrita')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'10', N'Corredores')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'6', N'11', N'Garabito')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'7', N'1', N'Limón')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'7', N'2', N'Pococí')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'7', N'3', N'Siquirres')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'7', N'4', N'Talamanca')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'7', N'5', N'Matina')
GO
INSERT [dbo].[Cantones] ([Cod_Provincia], [Cod_Canton], [Canton]) VALUES (N'7', N'6', N'Guácimo')
GO