INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'1', N'San Jose')
GO
INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'2', N'Alajuela')
GO
INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'3', N'Cartago')
GO
INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'4', N'Heredia')
GO
INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'5', N'Guanacaste')
GO
INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'6', N'Puntarenas')
GO
INSERT [dbo].[Provincias] ([Cod_Provincia], [Provincia]) VALUES (N'7', N'Limon')
GO