
INSERT INTO USUARIOS (Cod_Role,Cod_Provincia,Cod_Canton,Cod_Distrito,Cod_Posicion,Modo_Customizado,Foto,Nombre,Primer_Apellido,Segundo_Apellido,Fecha_Nacimiento,Telefono,Correo,Contrasena,Fecha,Intentos,Estatura,Peso,Apodo,Partidos_Jugados,Partidos_Jugador_Futplay, Descripcion_Estado )
VALUES ( 1, 4,1,1,1,1,'man-1.svg','Nelson','Morera','Fernandez','1996-08-14','506-6296-2461','workemailnelson@gmail.com','W3lcomeAb0ard','2022-01-13',0, 1.75,70,'Nevi',0,0,''),
( 2, 4,1,1,1,1,'man-2.svg','Xavier','Verdu','','2000-04-10','1-971-353-3554','xavi99vc@gmail.com','Welcome2021!','2022-01-13',0, 1.75,70,'Xavi',0,0,''),
( 3,4,1,1,1,1,'man-3.svg','Mauricio','Herra','','1985-04-10','506-7016-1650','mauricio.herra@gmail.com','Welcome2021!','2022-01-13',0, 1.75,70,'Mau',0,0,'')

