
INSERT INTO ROLES (Nombre)
VALUES ('Administrador') ,('Administrador Cancha - Cliente'),('Cliente')


INSERT INTO Horarios (Cod_Hora , Hora , Abreviacion)
VALUES  (1,'06', 'AM') , (2,'07', 'AM'),  (3,'08', 'AM'),  (4,'09', 'AM'),  (5,'10', 'AM'),  (6,'11', 'AM') , (7,'12', 'PM'),
        (8,'01', 'PM') , (9,'02', 'PM'),  (10,'03', 'PM'),  (11,'04', 'PM'),  (12,'05', 'PM'),  (13,'06', 'PM') , (14,'07', 'PM'),
		(15,'08', 'PM'),  (16,'09', 'PM'),  (17,'10', 'PM')
        