INSERT INTO EQUIPOS (Cod_Usuario,Cod_Provincia,Cod_Canton,Cod_Distrito,Foto,Nombre,Abreviacion,Fecha,Estrellas,Dureza,Posicion_Actual,Puntaje_Actual,Estado, Descripcion_Estado)
VALUES 
(7,4,1,1,'brazil.svg','Brazil','BZ','2022-01-13',2,'halo.svg',0,0,1,''), 
(7,4,1,1,'china.svg','China','CH','2022-01-13',3,'sad.svg',0,0,1,''),
(7,4,1,1,'germany.svg','Germany','GE','2022-01-13',3,'smiling-face.svg',0,0,1,''),
(7,4,1,1,'italy.svg','Italy','IT','2022-01-13',3,'frown.svg',0,0,1,''),
(7,4,1,1,'russia.svg','Russia','BZ','2022-01-13',3,'smiling.svg',0,0,1,''),
(7,4,1,1,'united-kingdom.svg','United Kingdom','UK','2022-01-13',3,'sad.svg',0,0,1,''),
(7,4,1,1,'france.svg','France','FR','2022-01-13',3,'meh.svg',0,0,1,''),
(7,4,1,1,'united-states.svg','United States','US','2022-01-13',3,'halo.svg',0,0,1,'')
