
export class JugadoresEquipos {
    constructor(
        public  Cod_Posicion: number,
        public Posicion: string,
        public Cod_Usuario: number,
        public Nombre: string,
        public Primer_Apellido: string,
        public Segundo_Apellido: string,
        public Foto: string,
        public Estatura: number,
        public Peso: number,
        public Apodo: string,
        public Partidos_Jugados: number,
        public Partidos_Jugador_Futplay: number,
        public Partidos_Jugador_Del_Partido : number,
        public Compartir_Datos : number,
        public Cod_Provincia: 4,
        public Provincia: string,
        public Telefono: string,
        public Cod_Canton: number,
        public Canton: string,
        public Cod_Distrito: number,
        public Distrito: string,
        public Cod_Equipo: number,
        public Abreviacion:string,
        public Nombre_Equipo: string,
        public Foto_Equipo: string,
        public Avatar:boolean,
        public Partidos_Ganados: number,
        public Partidos_Perdidos: number,
        public Goles_Favor : number,
        public Goles_Encontra :number,
        public Promedio_Altura_Jugadores : number,
        public Promedio_Peso_Jugadores :number,
        
    ){}
}
